name: flutter_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

assets:
  -

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^4.0.3
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2
  geolocator: ^12.0.0
  intl: ^0.19.0
  lottie: ^3.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  weather: ^3.1.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - 'lib/assets/'
    - 'assets/'
    - assets/alarm.mp3
    - 'assets/images/'
