name: flutter_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

assets:
  -

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  intl : ^0.19.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  android_alarm_manager_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - 'lib/assets/'
